# Generated by Django 3.0.3 on 2020-02-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('field', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('issueDate', models.DateField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('issueDate', models.DateField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('institution', models.CharField(max_length=100)),
                ('degreeName', models.CharField(max_length=100)),
                ('degreeTitle', models.CharField(max_length=15)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField()),
                ('summary', models.CharField(max_length=100, null=True)),
                ('images', models.ManyToManyField(to='portfolio.Image')),
                ('skills', models.ManyToManyField(to='portfolio.Skill')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('images', models.ManyToManyField(to='portfolio.Image')),
                ('skills', models.ManyToManyField(to='portfolio.Skill')),
            ],
        ),
    ]
